name: Run linter workflow with Black and Ruff
on:
  push:
    branches:
      - '**'

jobs:
  run-linter-with-Black-and-Ruff:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'staging' && 'staging' || github.ref_name == 'production' && 'production' || 'development' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.6'

      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-python-${{ hashFiles('dev-requirements.txt') }} 

      - name: Install dependencies
        run: |
          python -m venv venv 
          venv/bin/python -m pip install --upgrade pip
          if [ -f "dev-requirements.txt" ]; then venv/bin/python -m pip install -r dev-requirements.txt; fi 

      - name: Run Black
        run: |
          venv/bin/python -m black --check .

      - name: Run Ruff
        run: |
          venv/bin/python -m ruff .
